// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh85jirsSWg4AuwuG4gSJL0dJZCTrFO24',
    appId: '1:533027461303:web:76509ac6a2a5658029d532',
    messagingSenderId: '533027461303',
    projectId: 'uesr-auth',
    authDomain: 'uesr-auth.firebaseapp.com',
    storageBucket: 'uesr-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgwFz9PgTrwmIWjBx4NZVhBrUMrf1rc0o',
    appId: '1:533027461303:android:6e0b39165522df8429d532',
    messagingSenderId: '533027461303',
    projectId: 'uesr-auth',
    storageBucket: 'uesr-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYXM2MGVBlxRnAeyzqxyy3M_Xj_QjlrsI',
    appId: '1:533027461303:ios:3244bf235fa8111d29d532',
    messagingSenderId: '533027461303',
    projectId: 'uesr-auth',
    storageBucket: 'uesr-auth.appspot.com',
    iosBundleId: 'com.example.userAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYXM2MGVBlxRnAeyzqxyy3M_Xj_QjlrsI',
    appId: '1:533027461303:ios:fac8e7c1156c7de729d532',
    messagingSenderId: '533027461303',
    projectId: 'uesr-auth',
    storageBucket: 'uesr-auth.appspot.com',
    iosBundleId: 'com.example.userAuthApp.RunnerTests',
  );
}
